name: Preview

on:
  workflow_run:
    workflows:
      - Check
    types:
      - completed

env:
  CI: true
  FORCE_COLOR: true
  JAVA_VERSION: 11
  JAVA_DISTRIBUTION: temurin

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: preview
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
            wrappers
          arguments: assembleDebug
      - uses: actions/upload-artifact@v3
        with:
          name: preview-apk
          path: app/build/outputs/apk/debug/app-debug*.apk
