name: Release

on:
  push:
    branches:
      - main

env:
  CI: true
  FORCE_COLOR: true
  SEMANTIC_RELEASE: 18
  NODE_VERSION: 16

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]') && !contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm init --yes
      - run: npm install semantic-release@18 @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/git @semantic-release/github

      - uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: ${{ env.SEMANTIC_RELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Release Notification
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
